### ISSUE TITLE
抖音直播仅限手机观看获取不到直播流地址

### ISSUE THREAD

**Issue by zzh-999** [shixiuhai/sxhCrawlerFree#1]

**Comment by zzh-999** [comment]
这个问题可以解决吗

**Comment by shixiuhai** [comment]
报错信息是?我晚些提交解决一下，之前提交的最新应该是douyin_new.py
代码

**Comment by zzh-999** [comment]
data = json.loads(ress.text)  
仅限手机观看直播返回值是{"data":{"data":[{"id_str":"7302874619327892287","status":4,"status_str":"4","title":"还有一个小时就要起床了我还…","user_count_str":"0","mosaic_status":0,"mosaic_status_str":"","admin_user_ids":[],"admin_user_ids_str":[],"live_room_mode":3,"has_commerce_goods":false,"linker_map":{},"AnchorABMap":{},"like_count":0,"owner_user_id_str":""}],"enter_room_id":"7302874619327892287","user":{"id_str":"2532874320619312","sec_uid":"MS4wLjABAAAAVjs4z2sK2aGAdbKg0mocXThG5I6pAuAfT85qg48eNcqcl6jSHbhy7lt7SXpMvHiP","nickname":"景好好","avatar_thumb":{"url_list":["https://p6.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_f93006309059212f1ecf5dcc22ed1b4e.jpeg?from=3067671334","https://p26.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_f93006309059212f1ecf5dcc22ed1b4e.jpeg?from=3067671334","https://p11.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_f93006309059212f1ecf5dcc22ed1b4e.jpeg?from=3067671334"]},"follow_info":{"follow_status":0,"follow_status_str":"0"}},"qrcode_url":"","enter_mode":0,"room_status":2,"partition_road_map":{},"similar_rooms":[],"shark_decision_conf":""},"extra":{"now":1700336573145},"status_code":0}
None

是返回值为None的问题

仅限手机观看直播：
![image](https://github.com/shixiuhai/sxhCrawlerFree/assets/103309322/0f0cbe8b-f60b-4749-bd70-6162d5330d6e)

**Comment by zzh-999** [comment]
这个解决不了的话  就算了  抖音直播这种情况很少  我目前只遇到过一个主播是这样的

**Comment by shixiuhai** [comment]
这边我看了一片还是没有发现，这个原因我谷歌搜索看了一下，可能这个原因https://www.zhihu.com/question/491902093/answer/2448897495

**Comment by zzh-999** [comment]
好的  感谢
