### ISSUE TITLE
douyin_video.py怎样用？

### ISSUE THREAD

**Issue by RallyQ** [shixiuhai/sxhCrawlerFree#4]
douyin_video.py这个是获取抖音视频链接的脚本吧，目前能使用正常吗？
麻烦给指教一下怎么个用法？

**Comment by RallyQ** [comment]
通过PY运行了，信息显示【INFO:     Uvicorn running on http://127.0.0.1:9001 (Press CTRL+C to quit)】
bat怎样传递或调用这个地址？

**Comment by RallyQ** [comment]
是修改31行吗？                        "cookie": "ttwid=%s" % k
改成这样？                       "cookie": "ttwid=从浏览器获取的抖音cookie中的ttwid值"

**Comment by shixiuhai** [comment]
douyin_video.py 这是一个API接口服务, 抖音解析API是  需要使用postman或者apipost这里api接口请求工具调试，请求类型是post请求，本地请求接口是 http://127.0.0.1:9001/api/return_douyin/original_url,请求参数是formdata里添加 ， 传入参数是 douyin_share_url 这是一个手机端分享的端视频链接进行真链接地址解析

**Comment by RallyQ** [comment]
哦，挺复杂，不适合我用😁

**Comment by shixiuhai** [comment]
你可以使用gpt将上面代码替换成函数式调用，提示词可以比如把下面post接口代码替换成函数调用传参
